/**
* mysql-countries-languages.sql
* This sql file will populate all countries of the world as well
* as all languages spoken to your database.
* The whole project is done with. multiple languages
* to match your needs. 
*
* Feel free to contribute!
*
*
* Author: syr0s <daniel.noetzel@gmail.com>
* Maintainer: syr0s <daniel.noetzel@gmail.com>
* Version: 0.1.0
* License: GPL3
*
**/

/**
* TABLE OF CONTENT
* table creation
*    countries table
*    languages table
*    continents table
*    states table
*
* constraints
*    countries-states
*    continents-countries
*    languages-countries
*    
* insert values
*    continents (7 records)
*    languages (182 records)
*    countries
**/

/* table creation */
/* create table countries */
CREATE TABLE IF NOT EXISTS `countries` ( 
   `country_id` SMALLINT UNSIGNED NOT NULL COMMENT 'Primary key of the table. Didnt use auto increment to verify integrity',
   `country_name` JSON NOT NULL COMMENT 'json array of the country name in different languages',
   `capital_city` JSON NOT NULL COMMENT 'json array of the capital city in different languages',
   `official_name` JSON NOT NULL COMMENT 'json array of the official name in different languages',
   `official_language` SMALLINT UNSIGNED NOT NULL COMMENT 'Foreign key to table languages',
   `other_language` JSON COMMENT 'json array of other spoken languages',
   `continent` SMALLINT UNSIGNED NOT NULL COMMENT 'Foreign key to table continents',
   `country_codes` JSON NOT NULL COMMENT 'The different country codes',
   `currency` VARCHAR(3) NOT NULL COMMENT 'Currency in ISO 4217 format',
   `latitude` FLOAT NOT NULL COMMENT 'The latitude of the country',
   `longitude` FLOAT NOT NULL COMMENT 'The longitude of the country',
   `residents` BIGINT UNSIGNED COMMENT 'The residents of the country (can be null, if no data is available)',
   `area` INT UNSIGNED NOT NULL COMMENT 'Area of the country in square kilometers',
    PRIMARY KEY `Primary key`(
   `country_id`
    )
)
 COMMENT = 'table stores all countries with additional information"'
 ENGINE = InnoDB
 DEFAULT CHARACTER SET = utf8mb4
 ROW_FORMAT = Dynamic;

 /* create table languages */
CREATE TABLE IF NOT EXISTS `languages` ( 
   `language_id` SMALLINT UNSIGNED NOT NULL COMMENT 'Primary key of the table. Didnt use auto increment to verify integrity',
   `language_name` JSON NOT NULL COMMENT 'the language name in different languages',
   `language_codes` JSON NOT NULL COMMENT 'The different language codes',
   `speakers` BIGINT COMMENT 'worldwide speakers of the language',
   `continents` JSON NOT NULL COMMENT 'Continents the language is spoken',
    PRIMARY KEY `Primary key`(
   `language_id`
    )
)
 COMMENT = 'table stores all languages spoken on the world'
 ENGINE = InnoDB
 DEFAULT CHARACTER SET = utf8mb4
 ROW_FORMAT = Dynamic;

 /* create table continents */
CREATE TABLE IF NOT EXISTS `continents` ( 
   `continent_id` SMALLINT UNSIGNED NOT NULL COMMENT 'Primary key of the table. Didnt use auto increment to verify integrity',
   `continent_name` JSON NOT NULL COMMENT 'the language name in different languages',
   `residents` BIGINT UNSIGNED NOT NULL COMMENT 'Residents on this continent',
   `area` INT UNSIGNED NOT NULL COMMENT 'area in square kilometers',
    PRIMARY KEY `Primary key`(
   `continent_id`
    )
)
 COMMENT = 'table stores all continents with additional information'
 ENGINE = InnoDB
 DEFAULT CHARACTER SET = utf8mb4
 ROW_FORMAT = Dynamic;

 /* create table states */
CREATE TABLE IF NOT EXISTS `states` ( 
   `state_id` INT UNSIGNED NOT NULL COMMENT 'Primary key of the table. Didnt use auto increment to verify integrity',
   `country_id` SMALLINT UNSIGNED NOT NULL COMMENT 'Foreign key to table countries',
   `state_name` JSON NOT NULL COMMENT 'the state name in different languages',
   `state_capital` JSON COMMENT 'the states capital city as json array',
   `residents` BIGINT UNSIGNED COMMENT 'Residents in this state',
   `area` INT UNSIGNED COMMENT 'area in square kilometers',
    PRIMARY KEY `Primary key`(
   `state_id`
    )
)
 COMMENT = 'table stores all states with additional information'
 ENGINE = InnoDB
 DEFAULT CHARACTER SET = utf8mb4
 ROW_FORMAT = Dynamic;

/* add constraint countries-states */
ALTER TABLE `states` 
  ADD CONSTRAINT `countries-states`
  FOREIGN KEY ( 
   `country_id`
)   REFERENCES `countries`( 
   `country_id`
) ;

/* add constraint continents-countries */
ALTER TABLE `countries` 
  ADD CONSTRAINT `continents-countries`
  FOREIGN KEY ( 
   `continent`
)   REFERENCES `continents`( 
   `continent_id`
) ;

/* add constraint languages-countries */
ALTER TABLE `countries` 
  ADD CONSTRAINT `languages-countries`
  FOREIGN KEY ( 
   `official_language`
)   REFERENCES `languages`( 
   `language_id`
) ;



/* insert values */
/* continents */
/* source of the values: german Wikipedia */
INSERT INTO `continents` (
    `continent_id`, `continent_name`, `residents`, `area`
) VALUES (
    1,
    '{
        "en":"Africa",
        "es":"África",
        "pt":"África",
        "de":"Afrika",
        "ru":"Африка",
        "fr":"Afrique"
    }',
    1300000000,
    30221532
),
(
    2,
    '{
        "en":"Asia",
        "es":"Asia",
        "pt":"Ásia",
        "de":"Asien",
        "ru":"Азия",
        "fr":"Asie"
    }',
    4560667108,
    44579000
),
(
    3,
    '{
        "en":"Europe",
        "es":"Europa",
        "pt":"Europa",
        "de":"Europa",
        "ru":"Европа",
        "fr":"L\'Europe"
    }',
    746000000,
    10523000
),
(
    4,
    '{
        "en":"North America",
        "es":"Norteamérica",
        "pt":"América do Norte",
        "de":"Nordamerika",
        "ru":"Северная Америка",
        "fr":"Amérique du Nord"
    }',
    528750000,
    24930000
),
(
    5,
    '{
        "en":"South America",
        "es":"Sudamerica",
        "pt":"América do Sul",
        "de":"Südamerika",
        "ru":"Южная Америка",
        "fr":"Amérique du Sud"
    }',
    418000000,
    17843000
),
(
    6,
    '{
        "en":"Oceania",
        "es":"Oceanía",
        "pt":"Oceânia",
        "de":"Ozeanien",
        "ru":"Океания",
        "fr":"Océanie"
    }',
    8500000,
    397000
),
(
    7,
    '{
        "en":"Antarctica",
        "es":"Antártida",
        "pt":"Antártica",
        "de":"Antarktika",
        "ru":"Антарктида",
        "fr":"Antarctique"
    }',
    1106,
    14000000
);

/* languages */
INSERT IGNORE INTO `languages` (
    `language_id`, `language_name`, `language_codes`, `speakers`, `continents`
) VALUES (
    1,
    '{
        "en":"Abkhazian",
        "es":"Abjasio",
        "pt":"Abcásia",
        "de":"Abchasisch",
        "ru":"Абхазский",
        "fr":"Abkhaze"
    }',
    '{
        "639-1":"ab",
        "639-2-T":"abk",
        "639-2-B":"abk",
        "639-3":"abk"
    }',
    100000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    2,
    '{
        "en":"Afar",
        "es":"afar",
        "pt":"afar",
        "de":"Afar",
        "ru":"Афарский язык",
        "fr":"Afar"
    }',
     '{
        "639-1":"aa",
        "639-2-T":"aar",
        "639-2-B":"aar",
        "639-3":"aar"
    }',
    1973800,
    '{
        "continent_id": [1]
    }'
),
(
    3,
    '{
        "en":"Afrikaans",
        "es":"africaans",
        "pt":"afrikaans",
        "de":"Afrikaans",
        "ru":"африкаанс",
        "fr":"afrikaans"
    }',
    '{
        "639-1":"af",
        "639-2-T":"afr",
        "639-2-B":"afr",
        "639-3":"afr"
    }',
    7200000,
    '{
        "continent_id": [1]
    }'
),
(
    4,
    '{
        "en":"Akan",
        "es":"Akan",
        "pt":"Akan",
        "de":"Akan",
        "ru":"Акан",
        "fr":"Akan"
    }',
    '{
        "639-1":"ak",
        "639-2-T":"aka",
        "639-2-B":"aka",
        "639-3":"aka + 2"
    }',
    11000000,
    '{
        "continent_id": [1]
    }'
),
(
    5,
    '{
        "en":"Albanian",
        "es":"albanés",
        "pt":"albanês",
        "de":"albanisch",
        "ru":"албанский",
        "fr":"albanais"
    }',
    '{
        "639-1":"sq",
        "639-2-T":"sqi",
        "639-2-B":"alb",
        "639-3":"sqi + 4"
    }',
    7500000,
    '{
        "continent_id": [3, 4, 5, 6]
    }'
),
(
    6,
    '{
        "en":"Amharic",
        "es":"Amárico",
        "pt":"Amárico",
        "de":"Amharisch",
        "ru":"Амхарский",
        "fr":"Amharique"
    }',
    '{
        "639-1":"am",
        "639-2-T":"amh",
        "639-2-B":"amh",
        "639-3":"amh"
    }',
    22000000,
    '{
        "continent_id": [1]
    }'
),
(
    7,
    '{
        "en":"Arabic",
        "es":"Arábica",
        "pt":"árabe",
        "de":"Arabisch",
        "ru":"арабский",
        "fr":"arabe"
    }',
    '{
        "639-1":"ar",
        "639-2-T":"ara",
        "639-2-B":"ara",
        "639-3":"ara + 29"
    }',
    310000000,
    '{
        "continent_id": [1, 2, 3]
    }'
),
(
    8,
    '{
        "en":"Aragonese",
        "es":"Aragonés",
        "pt":"Aragonês",
        "de":"Aragonesisch",
        "ru":"Арагонский",
        "fr":"Aragonais"
    }',
    '{
        "639-1":"an",
        "639-2-T":"arg",
        "639-2-B":"arg",
        "639-3":"arg"
    }',
    50000,
    '{
        "continent_id": [3]
    }'
),
(
    9,
    '{
        "en":"Armenian",
        "es":"Armenio",
        "pt":"Armênio",
        "de":"Armenisch",
        "ru":"Армянский",
        "fr":"Arménien"
    }',
    '{
        "639-1":"hy",
        "639-2-T":"hye",
        "639-2-B":"arm",
        "639-3":"hye"
    }',
    6700000,
    '{
        "continent_id": [2]
    }'
),
(
    10,
    '{
        "en":"Assamese",
        "es":"Asamés",
        "pt":"Assamês",
        "de":"Assamesisch",
        "ru":"Ассамский",
        "fr":"Assamais"
    }',
    '{
        "639-1":"as",
        "639-2-T":"asm",
        "639-2-B":"asm",
        "639-3":"asm"
    }',
    14810000,
    '{
        "continent_id": [2]
    }'
),
(
    11,
    '{
        "en":"Avaric",
        "es":"Avarico",
        "pt":"Avaric",
        "de":"Avaric",
        "ru":"Аварский",
        "fr":"Avaric"
    }',
    '{
        "639-1":"av",
        "639-2-T":"ava",
        "639-2-B":"ava",
        "639-3":"ava"
    }',
    1000000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    12,
    '{
        "en":"Avestan",
        "es":"Avestan",
        "pt":"Avestan",
        "de":"Avestan",
        "ru":"Авестийский",
        "fr":"Avestan"
    }',
    '{
        "639-1":"ae",
        "639-2-T":"ave",
        "639-2-B":"ave",
        "639-3":"ave"
    }',
    null,
    '{
        "continent_id": [2]
    }'
),
(
    13,
    '{
        "en":"Aymara",
        "es":"aimara",
        "pt":"Aymara",
        "de":"Aymara",
        "ru":"аймара",
        "fr":"Aymara"
    }',
    '{
        "639-1":"ay",
        "639-2-T":"aym",
        "639-2-B":"aym",
        "639-3":"aym + 2"
    }',
    1677100,
    '{
        "continent_id": [5]
    }'
),
(
    14,
    '{
        "en":"Azerbaijani",
        "es":"Azerbaiyano",
        "pt":"Azerbaijani",
        "de":"Aserbaidschanisch",
        "ru":"Азербайджанский",
        "fr":"Azerbaïdjanais"
    }',
    '{
        "639-1":"az",
        "639-2-T":"aze",
        "639-2-B":"aze",
        "639-3":"aze + 2"
    }',
    23000000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    15,
    '{
        "en":"Bambara",
        "es":"Bambara",
        "pt":"Bambara",
        "de":"Bambara",
        "ru":"Бамбара",
        "fr":"Bambara"
    }',
    '{
        "639-1":"bm",
        "639-2-T":"bam",
        "639-2-B":"bam",
        "639-3":"bam"
    }',
    4100000,
    '{
        "continent_id": [1]
    }'
),
(
    16,
    '{
        "en":"Bashkir",
        "es":"Bashkir",
        "pt":"Bashkir",
        "de":"Baschkirisch",
        "ru":"Башкирский",
        "fr":"Bachkir"
    }',
    '{
        "639-1":"ba",
        "639-2-T":"bak",
        "639-2-B":"bak",
        "639-3":"bak"
    }',
    1200000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    17,
    '{
        "en":"Basque",
        "es":"Vasco",
        "pt":"Basco",
        "de":"baskisch",
        "ru":"Баскский",
        "fr":"basque"
    }',
    '{
        "639-1":"eu",
        "639-2-T":"eus",
        "639-2-B":"baq",
        "639-3":"eus"
    }',
    1185500,
    '{
        "continent_id": [3]
    }'
),
(
    18,
    '{
        "en":"Belarusian",
        "es":"Bielorruso",
        "pt":"Bielorusso",
        "de":"Belarussisch",
        "ru":"Белорусский",
        "fr":"Biélorusse"
    }',
    '{
        "639-1":"be",
        "639-2-T":"bel",
        "639-2-B":"bel",
        "639-3":"bel"
    }',
    5100000,
    '{
        "continent_id": [3]
    }'
),
(
    19,
    '{
        "en":"Bengali",
        "es":"bengalí",
        "pt":"bengali",
        "de":"Bengali",
        "ru":"Бенгальский",
        "fr":"bengali"
    }',
    '{
        "639-1":"bn",
        "639-2-T":"ben",
        "639-2-B":"ben",
        "639-3":"be"
    }',
    230000000,
    '{
        "continent_id": [2]
    }'
),
(
    20,
    '{
        "en":"Bihari languages",
        "es":"Idiomas bihari",
        "pt":"Línguas bihari",
        "de":"Bihari-Sprachen",
        "ru":"Языки бихари",
        "fr":"Langues bihari"
    }',
    '{
        "639-1":"bh",
        "639-2-T":"bih",
        "639-2-B":"bih",
        "639-3":null
    }',
    null,
    '{
        "continent_id": [2]
    }'
),
(
    21,
    '{
        "en":"Bislama",
        "es":"Bislama",
        "pt":"Bislama",
        "de":"Bislama",
        "ru":"Бислама",
        "fr":"Bislama"
    }',
    '{
        "639-1":"bi",
        "639-2-T":"bis",
        "639-2-B":"bis",
        "639-3":"bis"
    }',
    200000,
    '{
        "continent_id": [6]
    }'
),
(
    22,
    '{
        "en":"Bosnian",
        "es":"Bosnio",
        "pt":"Bósnio",
        "de":"bosnisch",
        "ru":"Боснийский",
        "fr":"Bosniaque"
    }',
    '{
        "639-1":"bs",
        "639-2-T":"bos",
        "639-2-B":"bos",
        "639-3":"bos"
    }',
    3000000,
    '{
        "continent_id": [3]
    }'
),
(
    23,
    '{
        "en":"Breton",
        "es":"Bretón",
        "pt":"Bretão",
        "de":"Bretonisch",
        "ru":"Бретонский",
        "fr":"Breton"
    }',
    '{
        "639-1":"br",
        "639-2-T":"bre",
        "639-2-B":"bre",
        "639-3":"bre"
    }',
    226000,
    '{
        "continent_id": [3]
    }'
),
(
    24,
    '{
        "en":"Bulgarian",
        "es":"Búlgaro",
        "pt":"Búlgaro",
        "de":"Bulgarisch",
        "ru":"болгарский",
        "fr":"bulgare"
    }',
    '{
        "639-1":"bg",
        "639-2-T":"bul",
        "639-2-B":"bul",
        "639-3":"bul"
    }',
    9000000,
    '{
        "continent_id": [3]
    }'
),
(
    25,
    '{
        "en":"Burmese",
        "es":"Birmano",
        "pt":"Birmanês",
        "de":"birmanisch",
        "ru":"Бирманский",
        "fr":"Birman"
    }',
    '{
        "639-1":"my",
        "639-2-T":"mya",
        "639-2-B":"bur",
        "639-3":"mya"
    }',
    33000000,
    '{
        "continent_id": [2]
    }'
),
(
    26,
    '{
        "en":"Catalan",
        "es":"Catalán",
        "pt":"Catalão",
        "de":"katalanisch",
        "ru":"Каталонский",
        "fr":"Catalan"
    }',
    '{
        "639-1":"ca",
        "639-2-T":"cat",
        "639-2-B":"cat",
        "639-3":"cat"
    }',
    4100000,
    '{
        "continent_id": [3]
    }'
),
(
    27,
    '{
        "en":"Chamorro",
        "es":"Chamorro",
        "pt":"Chamorro",
        "de":"Chamorro",
        "ru":"Чаморро",
        "fr":"Chamorro"
    }',
    '{
        "639-1":"ch",
        "639-2-T":"cha",
        "639-2-B":"cha",
        "639-3":"cha"
    }',
    58000,
    '{
        "continent_id": [2]
    }'
),
(
    28,
    '{
        "en":"Chechen",
        "es":"Checheno",
        "pt":"Checheno",
        "de":"Tschetschenisch",
        "ru":"Чеченский",
        "fr":"Tchétchène"
    }',
    '{
        "639-1":"ce",
        "639-2-T":"che",
        "639-2-B":"che",
        "639-3":"che"
    }',
    1400000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    29,
    '{
        "en":"Chichewa",
        "es":"Chichewa",
        "pt":"Chichewa",
        "de":"Chichewa",
        "ru":"Чичева",
        "fr":"Chichewa"
    }',
    '{
        "639-1":"ny",
        "639-2-T":"nya",
        "639-2-B":"nya",
        "639-3":"nya"
    }',
    12000000,
    '{
        "continent_id": [1]
    }'
),
(
    30,
    '{
        "en":"Chinese",
        "es":"Chino",
        "pt":"Chinês",
        "de":"Chinesisch",
        "ru":"китайский язык",
        "fr":"Chinois"
    }',
    '{
        "639-1":"zh",
        "639-2-T":"zho",
        "639-2-B":"chi",
        "639-3":"zho + 16"
    }',
    1200000000,
    '{
        "continent_id": [2, 3, 4]
    }'
),
(
    31,
    '{
        "en":"Chuvash",
        "es":"Chuvash",
        "pt":"Chuvash",
        "de":"Tschuwaschisch",
        "ru":"Чувашский",
        "fr":"Chuvash"
    }',
    '{
        "639-1":"cv",
        "639-2-T":"chv",
        "639-2-B":"chv",
        "639-3":"chv"
    }',
    1042989,
    '{
        "continent_id": [3]
    }'
),
(
    32,
    '{
        "en":"Cornish",
        "es":"de Cornualles",
        "pt":"Cornish",
        "de":"kornisch",
        "ru":"Корнуолл",
        "fr":"cornouaillais"
    }',
    '{
        "639-1":"kw",
        "639-2-T":"cor",
        "639-2-B":"cor",
        "639-3":"cor"
    }',
    500,
    '{
        "continent_id": [3]
    }'
),
(
    33,
    '{
        "en":"Corsican",
        "es":"corso",
        "pt":"Corso",
        "de":"Korsisch",
        "ru":"Корсиканский",
        "fr":"Corse"
    }',
    '{
        "639-1":"co",
        "639-2-T":"cos",
        "639-2-B":"cos",
        "639-3":"cos"
    }',
    125000,
    '{
        "continent_id": [3]
    }'
),
(
    34,
    '{
        "en":"Cree",
        "es":"Cree",
        "pt":"Cree",
        "de":"Cree",
        "ru":"Кри",
        "fr":"Cri"
    }',
    '{
        "639-1":"cr",
        "639-2-T":"cre",
        "639-2-B":"cre",
        "639-3":"cre + 6"
    }',
    96260,
    '{
        "continent_id": [4]
    }'
),
(
    35,
    '{
        "en":"Croatian",
        "es":"croata",
        "pt":"croata",
        "de":"kroatisch",
        "ru":"хорватский",
        "fr":"croate"
    }',
    '{
        "639-1":"hr",
        "639-2-T":"hrv",
        "639-2-B":"hrv",
        "639-3":"hrv"
    }',
    5600000,
    '{
        "continent_id": [3]
    }'
),
(
    36,
    '{
        "en":"Czech",
        "es":"Checo",
        "pt":"Tcheco",
        "de":"Tschechisch",
        "ru":"Чешский",
        "fr":"tchèque"
    }',
    '{
        "639-1":"cs",
        "639-2-T":"ces",
        "639-2-B":"cze",
        "639-3":"ces"
    }',
    10700000,
    '{
        "continent_id": [3]
    }'
),
(
    37,
    '{
        "en":"Danish",
        "es":"Danés",
        "pt":"dinamarquês",
        "de":"dänisch",
        "ru":"Датский",
        "fr":"Danois"
    }',
    '{
        "639-1":"da",
        "639-2-T":"dan",
        "639-2-B":"dan",
        "639-3":"dan"
    }',
    6000000,
    '{
        "continent_id": [3]
    }'
),
(
    38,
    '{
        "en":"Dutch",
        "es":"Holandés",
        "pt":"Holandês",
        "de":"Niederländisch",
        "ru":"нидерландский язык",
        "fr":"Néerlandais"
    }',
    '{
        "639-1":"nl",
        "639-2-T":"nld",
        "639-2-B":"dut",
        "639-3":"nld"
    }',
    29000000,
    '{
        "continent_id": [3, 5]
    }'
),
(
    39,
    '{
        "en":"Dzongkha",
        "es":"Dzongkha",
        "pt":"Dzongkha",
        "de":"Dzongkha",
        "ru":"Дзонгка",
        "fr":"Dzongkha"
    }',
    '{
        "639-1":"dz",
        "639-2-T":"dzo",
        "639-2-B":"dzo",
        "639-3":"dzo"
    }',
    640000,
    '{
        "continent_id": [2]
    }'
),
(
    40,
    '{
        "en":"English",
        "es":"Inglés",
        "pt":"Inglês",
        "de":"Englisch",
        "ru":"английский",
        "fr":"Anglais"
    }',
    '{
        "639-1":"en",
        "639-2-T":"eng",
        "639-2-B":"eng",
        "639-3":"eng"
    }',
    1150000,
    '{
        "continent_id": [3, 4, 6]
    }'
),
(
    41,
    '{
        "en":"Esperanto",
        "es":"esperanto",
        "pt":"esperanto",
        "de":"Esperanto",
        "ru":"эсперанто",
        "fr":"espéranto"
    }',
    '{
        "639-1":"eo",
        "639-2-T":"epo",
        "639-2-B":"epo",
        "639-3":"epo"
    }',
    2000000,
    '{
        "continent_id": [1, 2, 3, 4, 5, 6]
    }'
),
(
    42,
    '{
        "en":"Estonian",
        "es":"Estonio",
        "pt":"Estoniano",
        "de":"estnisch",
        "ru":"эстонский",
        "fr":"estonien"
    }',
    '{
        "639-1":"et",
        "639-2-T":"est",
        "639-2-B":"est",
        "639-3":"est + 2"
    }',
    1100000,
    '{
        "continent_id": [3]
    }'
),
(
    43,
    '{
        "en":"Ewe",
        "es":"oveja",
        "pt":"ovelha",
        "de":"Ewe",
        "ru":"овца",
        "fr":"Éwé"
    }',
    '{
        "639-1":"ee",
        "639-2-T":"ewe",
        "639-2-B":"ewe",
        "639-3":"ewe"
    }',
    5000000,
    '{
        "continent_id": [1]
    }'
),
(
    44,
    '{
        "en":"Faroese",
        "es":"Feroés",
        "pt":"Faroense",
        "de":"Färöer",
        "ru":"Фарерские острова",
        "fr":"Féroïen"
    }',
    '{
        "639-1":"fo",
        "639-2-T":"fao",
        "639-2-B":"fao",
        "639-3":"fao"
    }',
    72000,
    '{
        "continent_id": [3]
    }'
),
(
    45,
    '{
        "en":"Fijian",
        "es":"Fiyiano",
        "pt":"De Fiji",
        "de":"Fidschianisch",
        "ru":"Фиджийский",
        "fr":"Fidjien"
    }',
    '{
        "639-1":"fj",
        "639-2-T":"fij",
        "639-2-B":"fij",
        "639-3":"fij"
    }',
    339210,
    '{
        "continent_id": [6]
    }'
),
(
    46,
    '{
        "en":"Finnish",
        "es":"Finlandés",
        "pt":"Finlandês",
        "de":"finnisch",
        "ru":"Финский",
        "fr":"Finlandais"
    }',
    '{
        "639-1":"fi",
        "639-2-T":"fin",
        "639-2-B":"fin",
        "639-3":"fin"
    }',
    5400000,
    '{
        "continent_id": [3]
    }'
),
(
    47,
    '{
        "en":"French",
        "es":"Francés",
        "pt":"Francês",
        "de":"Französisch",
        "ru":"французский язык",
        "fr":"Français"
    }',
    '{
        "639-1":"fr",
        "639-2-T":"fra",
        "639-2-B":"fre",
        "639-3":"fra"
    }',
    274000000,
    '{
        "continent_id": [1, 3, 5]
    }'
),
(
    48,
    '{
        "en":"Fulah",
        "es":"Fulah",
        "pt":"Fulah",
        "de":"Fulah",
        "ru":"Фулах",
        "fr":"Fulah"
    }',
    '{
        "639-1":"ff",
        "639-2-T":"ful",
        "639-2-B":"ful",
        "639-3":"ful + 9"
    }',
    65000000,
    '{
        "continent_id": [1]
    }'
),
(
    49,
    '{
        "en":"Galician",
        "es":"Gallego",
        "pt":"Galego",
        "de":"galizisch",
        "ru":"Галицкий",
        "fr":"Galicien"
    }',
    '{
        "639-1":"gl",
        "639-2-T":"glg",
        "639-2-B":"glg",
        "639-3":"glg"
    }',
    2400000,
    '{
        "continent_id": [3]
    }'
),
(
    50,
    '{
        "en":"Georgian",
        "es":"Georgiano",
        "pt":"Georgiano",
        "de":"georgisch",
        "ru":"Грузинский",
        "fr":"Géorgien"
    }',
    '{
        "639-1":"ka",
        "639-2-T":"kat",
        "639-2-B":"geo",
        "639-3":"kat"
    }',
    3700000,
    '{
        "continent_id": [2]
    }'
),
(
    51,
    '{
        "en":"German",
        "es":"Alemán",
        "pt":"Alemã",
        "de":"Deutsch",
        "ru":"Немецкий",
        "fr":"Allemand"
    }',
    '{
        "639-1":"de",
        "639-2-T":"deu",
        "639-2-B":"ger",
        "639-3":"deu"
    }',
    95000000,
    '{
        "continent_id": [3]
    }'
),
(
    52,
    '{
        "en":"Greek",
        "es":"Griego",
        "pt":"Grego",
        "de":"griechisch",
        "ru":"Греческий",
        "fr":"Grec"
    }',
    '{
        "639-1":"el",
        "639-2-T":"ell",
        "639-2-B":"gre",
        "639-3":"ell"
    }',
    13400000,
    '{
        "continent_id": [3]
    }'
),
(
    53,
    '{
        "en":"Guarani",
        "es":"Guarani",
        "pt":"Guarani",
        "de":"Guarani",
        "ru":"Гуарани",
        "fr":"Guarani"
    }',
    '{
        "639-1":"gn",
        "639-2-T":"grn",
        "639-2-B":"grn",
        "639-3":"grn + 5"
    }',
    4850000,
    '{
        "continent_id": [5]
    }'
),
(
    54,
    '{
        "en":"Gujarati",
        "es":"Gujarati",
        "pt":"Guzerate",
        "de":"Gujarati",
        "ru":"Гуджарати",
        "fr":"Gujarati"
    }',
    '{
        "639-1":"gu",
        "639-2-T":"guj",
        "639-2-B":"guj",
        "639-3":"guj"
    }',
    56000000,
    '{
        "continent_id": [1, 2]
    }'
),
(
    55,
    '{
        "en":"Haitian",
        "es":"Haitiano",
        "pt":"Haitiano",
        "de":"haitianisch",
        "ru":"Гаитянский",
        "fr":"Haïtien"
    }',
    '{
        "639-1":"ht",
        "639-2-T":"hat",
        "639-2-B":"hat",
        "639-3":"hat"
    }',
    9600000,
    '{
        "continent_id": [4, 5]
    }'
),
(
    56,
    '{
        "en":"Hausa",
        "es":"Hausa",
        "pt":"Hausa",
        "de":"Hausa",
        "ru":"Хауса",
        "fr":"Haoussa"
    }',
    '{
        "639-1":"ha",
        "639-2-T":"hau",
        "639-2-B":"hau",
        "639-3":"hau"
    }',
    100000000,
    '{
        "continent_id": [1]
    }'
),
(
    57,
    '{
        "en":"Hebrew",
        "es":"Hebreo",
        "pt":"Hebraico",
        "de":"hebräisch",
        "ru":"иврит",
        "fr":"Hébreu"
    }',
    '{
        "639-1":"he",
        "639-2-T":"heb",
        "639-2-B":"heb",
        "639-3":"heb"
    }',
    5000000,
    '{
        "continent_id": [1, 2, 3]
    }'
),
(
    58,
    '{
        "en":"Herero",
        "es":"Herero",
        "pt":"Herero",
        "de":"Herero",
        "ru":"Гереро",
        "fr":"Herero"
    }',
    '{
        "639-1":"hz",
        "639-2-T":"her",
        "639-2-B":"her",
        "639-3":"her"
    }',
    211700,
    '{
        "continent_id": [1]
    }'
),
(
    59,
    '{
        "en":"Hindi",
        "es":"Hindi",
        "pt":"Hindi",
        "de":"Hindi",
        "ru":"хинди",
        "fr":"Hindi"
    }',
    '{
        "639-1":"hi",
        "639-2-T":"hin",
        "639-2-B":"hin",
        "639-3":"hin"
    }',
    322000000,
    '{
        "continent_id": [2]
    }'
),
(
    60,
    '{
        "en":"Hiri Motu",
        "es":"Hiri Motu",
        "pt":"Hiri Motu",
        "de":"Hiri Motu",
        "ru":"Хири Моту",
        "fr":"Hiri Motu"
    }',
    '{
        "639-1":"ho",
        "639-2-T":"hmo",
        "639-2-B":"hmo",
        "639-3":"hmo"
    }',
    6000000,
    '{
        "continent_id": [6]
    }'
),
(
    61,
    '{
        "en":"Hungarian",
        "es":"Húngaro",
        "pt":"Húngaro",
        "de":"ungarisch",
        "ru":"венгерский язык",
        "fr":"Hongrois"
    }',
    '{
        "639-1":"hu",
        "639-2-T":"hun",
        "639-2-B":"hun",
        "639-3":"hun"
    }',
    13000000,
    '{
        "continent_id": [3]
    }'
),
(
    62,
    '{
        "en":"Indonesian",
        "es":"Indonesio",
        "pt":"Indonésio",
        "de":"Indonesisch",
        "ru":"индонезийский",
        "fr":"Indonésien"
    }',
    '{
        "639-1":"id",
        "639-2-T":"ind",
        "639-2-B":"ind",
        "639-3":"ind"
    }',
    43000000,
    '{
        "continent_id": [2]
    }'
),
(
    63,
    '{
        "en":"Interlingua",
        "es":"Interlingua",
        "pt":"Interlíngua",
        "de":"Interlingua",
        "ru":"Интерлингва",
        "fr":"Interlingua"
    }',
    '{
        "639-1":"ia",
        "639-2-T":"ina",
        "639-2-B":"ina",
        "639-3":"ina"
    }',
    1500,
    '{
        "continent_id": [3]
    }'
),
(
    64,
    '{
        "en":"Irish",
        "es":"Irlandés",
        "pt":"Irlandês",
        "de":"irisch",
        "ru":"Ирландский",
        "fr":"Irlandais"
    }',
    '{
        "639-1":"ga",
        "639-2-T":"gle",
        "639-2-B":"gle",
        "639-3":"gle"
    }',
    170290,
    '{
        "continent_id": [3]
    }'
),
(
    65,
    '{
        "en":"Igbo",
        "es":"Igbo",
        "pt":"Igbo",
        "de":"Igbo",
        "ru":"Игбо",
        "fr":"Igbo"
    }',
    '{
        "639-1":"ig",
        "639-2-T":"ibo",
        "639-2-B":"ibo",
        "639-3":"ibo"
    }',
    35000000,
    '{
        "continent_id": [1]
    }'
),
(
    66,
    '{
        "en":"Inupiaq",
        "es":"Inupiaq",
        "pt":"Inupiaq",
        "de":"Inupiaq",
        "ru":"Инупиак",
        "fr":"Inupiaq"
    }',
    '{
        "639-1":"ik",
        "639-2-T":"ipk",
        "639-2-B":"ipk",
        "639-3":"ipk + 2"
    }',
    2144,
    '{
        "continent_id": [4]
    }'
),
(
    67,
    '{
        "en":"Ido",
        "es":"ido",
        "pt":"ido",
        "de":"Ido",
        "ru":"идо",
        "fr":"ido"
    }',
    '{
        "639-1":"io",
        "639-2-T":"ido",
        "639-2-B":"ido",
        "639-3":"ido"
    }',
    200,
    '{
        "continent_id": [3]
    }'
),
(
    68,
    '{
        "en":"Icelandic",
        "es":"Islandés",
        "pt":"islandês",
        "de":"isländisch",
        "ru":"исландский",
        "fr":"islandais"
    }',
    '{
        "639-1":"is",
        "639-2-T":"isl",
        "639-2-B":"ice",
        "639-3":"isl"
    }',
    314000,
    '{
        "continent_id": [3]
    }'
),
(
    69,
    '{
        "en":"Italian",
        "es":"Italiano",
        "pt":"Italiano",
        "de":"italienisch",
        "ru":"Итальянский",
        "fr":"Italien"
    }',
    '{
        "639-1":"it",
        "639-2-T":"ita",
        "639-2-B":"ita",
        "639-3":"ita"
    }',
    67000000,
    '{
        "continent_id": [3, 4]
    }'
),
(
    70,
    '{
        "en":"Inuktitut",
        "es":"Inuktitut",
        "pt":"Inuktitut",
        "de":"Inuktitut",
        "ru":"Инуктитут",
        "fr":"Inuktitut"
    }',
    '{
        "639-1":"iu",
        "639-2-T":"iku",
        "639-2-B":"iku",
        "639-3":"iku + 2"
    }',
    35215,
    '{
        "continent_id": [4]
    }'
),
(
    71,
    '{
        "en":"Japanese",
        "es":"Japonés",
        "pt":"Japonês",
        "de":"japanisch",
        "ru":"японский язык",
        "fr":"Japonais"
    }',
    '{
        "639-1":"ja",
        "639-2-T":"jpn",
        "639-2-B":"jpn",
        "639-3":"jpn"
    }',
    128000000,
    '{
        "continent_id": [2, 4]
    }'
),
(
    72,
    '{
        "en":"Javanese",
        "es":"Javanés",
        "pt":"Javanês",
        "de":"Javanisch",
        "ru":"Яванский",
        "fr":"Javanais"
    }',
    '{
        "639-1":"jv",
        "639-2-T":"jav",
        "639-2-B":"jav",
        "639-3":"jav"
    }',
    82000000,
    '{
        "continent_id": [2]
    }'
),
(
    73,
    /* also known as Kalaallisut */
    '{
        "en":"Greenlandic",
        "es":"Groenlandés",
        "pt":"Groenlandês",
        "de":"Grönländisch",
        "ru":"Гренландский",
        "fr":"groenlandais"
    }',
    '{
        "639-1":"kl",
        "639-2-T":"kal",
        "639-2-B":"kal",
        "639-3":"kal"
    }',
    57000,
    '{
        "continent_id": [4]
    }'
),
(
    74,
    '{
        "en":"Kannada",
        "es":"Canarés",
        "pt":"Canarim",
        "de":"Kannada",
        "ru":"Каннада",
        "fr":"Kannada"
    }',
    '{
        "639-1":"kn",
        "639-2-T":"kan",
        "639-2-B":"kan",
        "639-3":"kan"
    }',
    52000000,
    '{
        "continent_id": [2]
    }'
),
(
    75,
    '{
        "en":"Kanuri",
        "es":"Kanuri",
        "pt":"Kanuri",
        "de":"Kanuri",
        "ru":"Канури",
        "fr":"Kanuri"
    }',
    '{
        "639-1":"kr",
        "639-2-T":"kau",
        "639-2-B":"kau",
        "639-3":"kau + 3"
    }',
    8600000,
    '{
        "continent_id": [1]
    }'
),
(
    76,
    '{
        "en":"Kashmiri",
        "es":"Cachemira",
        "pt":"Caxemira",
        "de":"Kashmiri",
        "ru":"Кашмири",
        "fr":"Cachemire"
    }',
    '{
        "639-1":"ks",
        "639-2-T":"kas",
        "639-2-B":"kas",
        "639-3":"kas"
    }',
    7000000,
    '{
        "continent_id": [2]
    }'
),
(
    77,
    '{
        "en":"Kazakh",
        "es":"Kazajo",
        "pt":"Cazaque",
        "de":"Kasachisch",
        "ru":"Казахский",
        "fr":"Kazakh"
    }',
    '{
        "639-1":"kk",
        "639-2-T":"kaz",
        "639-2-B":"kaz",
        "639-3":"kaz"
    }',
    22000000,
    '{
        "continent_id": [2]
    }'
),
(
    78,
    '{
        "en":"Khmer",
        "es":"Jemer",
        "pt":"Khmer",
        "de":"Khmer",
        "ru":"Кхмерский",
        "fr":"Khmer"
    }',
    '{
        "639-1":"km",
        "639-2-T":"khm",
        "639-2-B":"khm",
        "639-3":"khm"
    }',
    16000000,
    '{
        "continent_id": [2]
    }'
),
(
    79,
    '{
        "en":"Kikuyu",
        "es":"Kikuyu",
        "pt":"Kikuyu",
        "de":"Kikuyu",
        "ru":"Кикую",
        "fr":"Kikuyu"
    }',
    '{
        "639-1":"ki",
        "639-2-T":"kik",
        "639-2-B":"kik",
        "639-3":"kik"
    }',
    6600000,
    '{
        "continent_id": [1]
    }'
),
(
    80,
    '{
        "en":"Kinyarwanda",
        "es":"Kinyarwanda",
        "pt":"Kinyarwanda",
        "de":"Kinyarwanda",
        "ru":"Киньяруанда",
        "fr":"Kinyarwanda"
    }',
    '{
        "639-1":"rw",
        "639-2-T":"kin",
        "639-2-B":"kin",
        "639-3":"kin"
    }',
    9800000,
    '{
        "continent_id": [1]
    }'
),
(
    81,
    '{
        "en":"Kyrgyz",
        "es":"Kirguís",
        "pt":"Quirguiz",
        "de":"Kirgisisch",
        "ru":"Кыргызский",
        "fr":"Kirghiz"
    }',
    '{
        "639-1":"ky",
        "639-2-T":"kir",
        "639-2-B":"kir",
        "639-3":"kir"
    }',
    4300000,
    '{
        "continent_id": [2]
    }'
),
(
    82,
    '{
        "en":"Komi",
        "es":"Komi",
        "pt":"Komi",
        "de":"Komi",
        "ru":"Коми",
        "fr":"Komi"
    }',
    '{
        "639-1":"kv",
        "639-2-T":"kom",
        "639-2-B":"kom",
        "639-3":"kom + 2"
    }',
    160000,
    '{
        "continent_id": [2]
    }'
),
(
    83,
    '{
        "en":"Kongo",
        "es":"Kongo",
        "pt":"Kongo",
        "de":"Kongo",
        "ru":"Конго",
        "fr":"Kongo"
    }',
    '{
        "639-1":"kg",
        "639-2-T":"kon",
        "639-2-B":"kon",
        "639-3":"kon + 3"
    }',
    6500000,
    '{
        "continent_id": [1]
    }'
),
(
    84,
    '{
        "en":"Korean",
        "es":"Coreano",
        "pt":"Coreano",
        "de":"Koreanisch",
        "ru":"корейский язык",
        "fr":"coréen"
    }',
    '{
        "639-1":"ko",
        "639-2-T":"kor",
        "639-2-B":"kor",
        "639-3":"kor"
    }',
    77200000,
    '{
        "continent_id": [2]
    }'
),
(
    85,
    '{
        "en":"Kurdish",
        "es":"Kurdo",
        "pt":"curdo",
        "de":"kurdisch",
        "ru":"Курдский",
        "fr":"kurde"
    }',
    '{
        "639-1":"ku",
        "639-2-T":"kur",
        "639-2-B":"kur",
        "639-3":"kur + 3"
    }',
    30000000,
    '{
        "continent_id": [2]
    }'
),
(
    86,
    '{
        "en":"Kuanyama",
        "es":"Kuanyama",
        "pt":"Kuanyama",
        "de":"Kuanyama",
        "ru":"Куаньяма",
        "fr":"Kuanyama"
    }',
    '{
        "639-1":"kj",
        "639-2-T":"kua",
        "639-2-B":"kua",
        "639-3":"kua"
    }',
    690000,
    '{
        "continent_id": [1]
    }'
),
(
    87,
    '{
        "en":"Latin",
        "es":"Latino",
        "pt":"Latino",
        "de":"Latein",
        "ru":"латинский",
        "fr":"Latin"
    }',
    '{
        "639-1":"la",
        "639-2-T":"lat",
        "639-2-B":"lat",
        "639-3":"lat"
    }',
    null,
    '{
        "continent_id": [3]
    }'
),
(
    88,
    '{
        "en":"Luxembourgish",
        "es":"Luxemburgués",
        "pt":"Luxemburguês",
        "de":"Luxemburgisch",
        "ru":"Люксембургский",
        "fr":"Luxembourgeois"
    }',
    '{
        "639-1":"lb",
        "639-2-T":"ltz",
        "639-2-B":"ltz",
        "639-3":"ltz"
    }',
    390000,
    '{
        "continent_id": [3]
    }'
),
(
    89,
    '{
        "en":"Ganda",
        "es":"Ganda",
        "pt":"Ganda",
        "de":"Ganda",
        "ru":"Ганда",
        "fr":"Ganda"
    }',
    '{
        "639-1":"lg",
        "639-2-T":"lug",
        "639-2-B":"lug",
        "639-3":"lug"
    }',
    8500000,
    '{
        "continent_id": [1]
    }'
),
(
    90,
    '{
        "en":"Limburgish",
        "es":"Limburgués",
        "pt":"Limburguês",
        "de":"Limburgisch",
        "ru":"Лимбургский",
        "fr":"Limbourgeois"
    }',
    '{
        "639-1":"li",
        "639-2-T":"lim",
        "639-2-B":"lim",
        "639-3":"lim"
    }',
    1300000,
    '{
        "continent_id": [3]
    }'
),
(
    91,
    '{
        "en":"Lingala",
        "es":"Lingala",
        "pt":"Lingala",
        "de":"Lingala",
        "ru":"Лингала",
        "fr":"Lingala"
    }',
    '{
        "639-1":"ln",
        "639-2-T":"lin",
        "639-2-B":"lin",
        "639-3":"lin"
    }',
    15000000,
    '{
        "continent_id": [1]
    }'
),
(
    92,
    '{
        "en":"Lao",
        "es":"Lao",
        "pt":"Lao",
        "de":"Lao",
        "ru":"Лаосский",
        "fr":"Laotien"
    }',
    '{
        "639-1":"lo",
        "639-2-T":"lao",
        "639-2-B":"lao",
        "639-3":"lao"
    }',
    30000000,
    '{
        "continent_id": [2]
    }'
),
(
    93,
    '{
        "en":"Lithuanian",
        "es":"Lituano",
        "pt":"Lituano",
        "de":"litauisch",
        "ru":"Литовский",
        "fr":"Lituanien"
    }',
    '{
        "639-1":"lt",
        "639-2-T":"lit",
        "639-2-B":"lit",
        "639-3":"lit"
    }',
    3000000,
    '{
        "continent_id": [3]
    }'
),
(
    94,
    '{
        "en":"Luba-Katanga",
        "es":"Luba-Katanga",
        "pt":"Luba-Katanga",
        "de":"Luba-Katanga",
        "ru":"Люба-Катанга",
        "fr":"Luba-Katanga"
    }',
    '{
        "639-1":"lu",
        "639-2-T":"lub",
        "639-2-B":"lub",
        "639-3":"lub"
    }',
    1505000,
    '{
        "continent_id": [1]
    }'
),
(
    95,
    '{
        "en":"Latvian",
        "es":"Letón",
        "pt":"Letão",
        "de":"lettisch",
        "ru":"Латышский",
        "fr":"letton"
    }',
    '{
        "639-1":"lv",
        "639-2-T":"lav",
        "639-2-B":"lav",
        "639-3":"lav + 2"
    }',
    1750000,
    '{
        "continent_id": [3]
    }'
),
(
    96,
    '{
        "en":"Manx",
        "es":"lengua de la isla de Man",
        "pt":"Manx",
        "de":"Manx",
        "ru":"Манкс",
        "fr":"Manx"
    }',
    '{
        "639-1":"gv",
        "639-2-T":"glv",
        "639-2-B":"glv",
        "639-3":"glv"
    }',
    1800,
    '{
        "continent_id": [3]
    }'
),
(
    97,
    '{
        "en":"Macedonian",
        "es":"macedónio",
        "pt":"Macedônio",
        "de":"mazedonisch",
        "ru":"македонский",
        "fr":"Macédonien"
    }',
    '{
        "639-1":"mk",
        "639-2-T":"mkd",
        "639-2-B":"mac",
        "639-3":"mkd"
    }',
    3500000,
    '{
        "continent_id": [3]
    }'
),
(
    98,
    '{
        "en":"Malagasy",
        "es":"madagascarí",
        "pt":"malgaxe",
        "de":"Madagassisch",
        "ru":"Малагасийский",
        "fr":"malgache"
    }',
    '{
        "639-1":"mg",
        "639-2-T":"mlg",
        "639-2-B":"mlg",
        "639-3":"mlg + 11"
    }',
    25000000,
    '{
        "continent_id": [1]
    }'
),
(
    99,
    '{
        "en":"Malay",
        "es":"Malayo",
        "pt":"Malaio",
        "de":"malaiisch",
        "ru":"малайский",
        "fr":"Malais"
    }',
    '{
        "639-1":"ms",
        "639-2-T":"msa",
        "639-2-B":"mya",
        "639-3":"msa + 36"
    }',
    250000000,
    '{
        "continent_id": [1]
    }'
),
(
    100,
    '{
        "en":"Malayalam",
        "es":"Malayalam",
        "pt":"Malayalam",
        "de":"Malayalam",
        "ru":"Малаялам",
        "fr":"Malayalam"
    }',
    '{
        "639-1":"ml",
        "639-2-T":"mal",
        "639-2-B":"mal",
        "639-3":"mal"
    }',
    45000000,
    '{
        "continent_id": [2]
    }'
),
(
    101,
    '{
        "en":"Maltese",
        "es":"Maltés",
        "pt":"Maltês",
        "de":"maltesisch",
        "ru":"Мальтийский",
        "fr":"maltais"
    }',
    '{
        "639-1":"mt",
        "639-2-T":"mlt",
        "639-2-B":"mlt",
        "639-3":"mlt"
    }',
    520000,
    '{
        "continent_id": [3]
    }'
),
(
    102,
    '{
        "en":"Maori",
        "es":"maorí",
        "pt":"maori",
        "de":"Maori",
        "ru":"маори",
        "fr":"Maori"
    }',
    '{
        "639-1":"mi",
        "639-2-T":"mri",
        "639-2-B":"mao",
        "639-3":"mri"
    }',
    50000,
    '{
        "continent_id": [6]
    }'
),
(
    103,
    '{
        "en":"Marathi",
        "es":"Marathi",
        "pt":"Marati",
        "de":"Marathi",
        "ru":"Маратхи",
        "fr":"Marathi"
    }',
    '{
        "639-1":"mr",
        "639-2-T":"mar",
        "639-2-B":"mar",
        "639-3":"mar"
    }',
    83000000,
    '{
        "continent_id": [2]
    }'
),
(
    104,
    '{
        "en":"Marshallese",
        "es":"Marshalés",
        "pt":"Marshallês",
        "de":"Marshallese",
        "ru":"Маршалльский",
        "fr":"Marshallese"
    }',
    '{
        "639-1":"mh",
        "639-2-T":"mah",
        "639-2-B":"mah",
        "639-3":"mah"
    }',
    55000,
    '{
        "continent_id": [6]
    }'
),
(
    105,
    '{
        "en":"Mongolian",
        "es":"Mongol",
        "pt":"mongol",
        "de":"mongolisch",
        "ru":"Монгольский",
        "fr":"Mongol"
    }',
    '{
        "639-1":"mn",
        "639-2-T":"mon",
        "639-2-B":"mon",
        "639-3":"mon + 2"
    }',
    5200000,
    '{
        "continent_id": [2]
    }'
),
(
    106,
    '{
        "en":"Nauru",
        "es":"Nauru",
        "pt":"Nauru",
        "de":"Nauru",
        "ru":"Науру",
        "fr":"Nauru"
    }',
    '{
        "639-1":"na",
        "639-2-T":"nau",
        "639-2-B":"nau",
        "639-3":"nau"
    }',
    6000,
    '{
        "continent_id": [6]
    }'
),
(
    107,
    '{
        "en":"Navajo",
        "es":"Navajo",
        "pt":"Navajo",
        "de":"Navajo",
        "ru":"Навахо",
        "fr":"Navajo"
    }',
    '{
        "639-1":"nv",
        "639-2-T":"nav",
        "639-2-B":"nav",
        "639-3":"nav"
    }',
    169359,
    '{
        "continent_id": [4]
    }'
),
(
    108,
    '{
        "en":"Ndebele",
        "es":"Ndebele",
        "pt":"Ndebele",
        "de":"Ndebele",
        "ru":"Ндебеле",
        "fr":"Ndebele"
    }',
    '{
        "639-1":"nd",
        "639-2-T":"nde",
        "639-2-B":"nde",
        "639-3":"nde"
    }',
    1600000,
    '{
        "continent_id": [1]
    }'
),
(
    109,
    '{
        "en":"Nepali",
        "es":"Nepalí",
        "pt":"Nepalês",
        "de":"Nepali",
        "ru":"Непальский",
        "fr":"Népalais"
    }',
    '{
        "639-1":"ne",
        "639-2-T":"nep",
        "639-2-B":"nep",
        "639-3":"nep + 2"
    }',
    16000000,
    '{
        "continent_id": [2]
    }'
),
(
    110,
    '{
        "en":"Ndonga",
        "es":"Ndonga",
        "pt":"Ndonga",
        "de":"Ndonga",
        "ru":"Ндонга",
        "fr":"Ndonga"
    }',
    '{
        "639-1":"ng",
        "639-2-T":"ndo",
        "639-2-B":"ndo",
        "639-3":"ndo"
    }',
    810000,
    '{
        "continent_id": [1]
    }'
),
(
    111,
    '{
        "en":"Norwegian Bokmål",
        "es":"Noruego bokmål",
        "pt":"Bokmål norueguês",
        "de":"Norwegischer Bokmål",
        "ru":"Норвежский букмол",
        "fr":"Norvégien bokmål"
    }',
    '{
        "639-1":"nb",
        "639-2-T":"nob",
        "639-2-B":"nob",
        "639-3":"nob"
    }',
    null,
    '{
        "continent_id": [3]
    }'
),
(
    112,
    '{
        "en":"Norwegian Nynorsk",
        "es":"Noruego Nynorsk",
        "pt":"Nynorsk norueguês",
        "de":"Norwegischer Nynorsk",
        "ru":"Норвежский нюнорск",
        "fr":"Norvégien nynorsk"
    }',
    '{
        "639-1":"nn",
        "639-2-T":"nno",
        "639-2-B":"nno",
        "639-3":"nno"
    }',
    null,
    '{
        "continent_id": [3]
    }'
),
(
    113,
    '{
        "en":"Norwegian",
        "es":"Noruego",
        "pt":"Norueguês",
        "de":"norwegisch",
        "ru":"Норвежский",
        "fr":"Norvégien"
    }',
    '{
        "639-1":"no",
        "639-2-T":"nor",
        "639-2-B":"nor",
        "639-3":"nor + 2"
    }',
    5320000,
    '{
        "continent_id": [3]
    }'
),
(
    114,
    '{
        "en":"Sichuan Yi",
        "es":"Sichuan Yi",
        "pt":"Sichuan Yi",
        "de":"Sichuan Yi",
        "ru":"Сычуань Йи",
        "fr":"Sichuan Yi"
    }',
    '{
        "639-1":"ii",
        "639-2-T":"iii",
        "639-2-B":"iii",
        "639-3":"iii"
    }',
    2000000,
    '{
        "continent_id": [2]
    }'
),
(
    115,
    '{
        "en":"Ndebele",
        "es":"Ndebele",
        "pt":"Ndebele",
        "de":"Ndebele",
        "ru":"Ндебеле",
        "fr":"Ndebele"
    }',
    '{
        "639-1":"nr",
        "639-2-T":"nbl",
        "639-2-B":"nbl",
        "639-3":"nbl"
    }',
    1100000,
    '{
        "continent_id": [1]
    }'
),
(
    116,
    '{
        "en":"Occitan",
        "es":"Occitano",
        "pt":"Occitano",
        "de":"Okzitanisch",
        "ru":"Окситанский",
        "fr":"Occitan"
    }',
    '{
        "639-1":"oc",
        "639-2-T":"oci",
        "639-2-B":"oci",
        "639-3":"oci"
    }',
    800000,
    '{
        "continent_id": [3]
    }'
),
(
    117,
    '{
        "en":"Ojibwa",
        "es":"Ojibwa",
        "pt":"Ojibwa",
        "de":"Ojibwa",
        "ru":"Оджибва",
        "fr":"Ojibwa"
    }',
    '{
        "639-1":"oj",
        "639-2-T":"oji",
        "639-2-B":"oji",
        "639-3":"oji + 7"
    }',
    100880,
    '{
        "continent_id": [4]
    }'
),
(
    118,
    '{
        "en":"Church Slavic",
        "es":"Iglesia eslava",
        "pt":"Igreja eslava",
        "de":"Kirchenslawisch",
        "ru":"Церковнославянский",
        "fr":"Église slave"
    }',
    '{
        "639-1":"cu",
        "639-2-T":"chu",
        "639-2-B":"chu",
        "639-3":"chu"
    }',
    null,
    '{
        "continent_id": [2, 3]
    }'
),
(
    119,
    '{
        "en":"Oromo",
        "es":"Oromo",
        "pt":"Oromo",
        "de":"Oromo",
        "ru":"Оромо",
        "fr":"Oromo"
    }',
    '{
        "639-1":"om",
        "639-2-T":"orm",
        "639-2-B":"orm",
        "639-3":"orm + 4"
    }',
    37000000,
    '{
        "continent_id": [1]
    }'
),
(
    120,
    '{
        "en":"Oriya",
        "es":"Oriya",
        "pt":"Oriya",
        "de":"Oriya",
        "ru":"Ория",
        "fr":"Oriya"
    }',
    '{
        "639-1":"or",
        "639-2-T":"ori",
        "639-2-B":"ori",
        "639-3":"ori + 2"
    }',
    35000000,
    '{
        "continent_id": [2]
    }'
),
(
    121,
    '{
        "en":"Ossetic",
        "es":"Osético",
        "pt":"Ossético",
        "de":"Ossetisch",
        "ru":"Осетинский",
        "fr":"Ossétique"
    }',
    '{
        "639-1":"os",
        "639-2-T":"oss",
        "639-2-B":"oss",
        "639-3":"oss"
    }',
    600000,
    '{
        "continent_id": [2]
    }'
),
(
    122,
    '{
        "en":"Punjabi",
        "es":"punjabi",
        "pt":"Punjabi",
        "de":"Punjabi",
        "ru":"Пенджаби",
        "fr":"Punjabi"
    }',
    '{
        "639-1":"pa",
        "639-2-T":"pan",
        "639-2-B":"pan",
        "639-3":"pan"
    }',
    125000000,
    '{
        "continent_id": [2]
    }'
),
(
    123,
    '{
        "en":"Pali",
        "es":"Pali",
        "pt":"Pali",
        "de":"Pali",
        "ru":"пали",
        "fr":"Pali"
    }',
    '{
        "639-1":"pi",
        "639-2-T":"pli",
        "639-2-B":"pli",
        "639-3":"pli"
    }',
    null,
    '{
        "continent_id": [2]
    }'
),
(
    124,
    '{
        "en":"Persian",
        "es":"persa",
        "pt":"persa",
        "de":"persisch",
        "ru":"Персидский",
        "fr":"Persan"
    }',
    '{
        "639-1":"fa",
        "639-2-T":"fas",
        "639-2-B":"per",
        "639-3":"fas + 2"
    }',
    110000000,
    '{
        "continent_id": [2]
    }'
),
(
    125,
    '{
        "en":"Polish",
        "es":"polaco",
        "pt":"polonesa",
        "de":"polnisch",
        "ru":"Польский",
        "fr":"polonaise"
    }',
    '{
        "639-1":"pl",
        "639-2-T":"pol",
        "639-2-B":"pol",
        "639-3":"pol"
    }',
    45000000,
    '{
        "continent_id": [3]
    }'
),
(
    126,
    '{
        "en":"Pashto",
        "es":"Pashto",
        "pt":"Pashto",
        "de":"Paschtu",
        "ru":"Пушту",
        "fr":"Pashto"
    }',
    '{
        "639-1":"ps",
        "639-2-T":"pus",
        "639-2-B":"pus",
        "639-3":"pus + 3"
    }',
    60000000,
    '{
        "continent_id": [2]
    }'
),
(
    127,
    '{
        "en":"Portuguese",
        "es":"Portugués",
        "pt":"Português",
        "de":"Portugiesisch",
        "ru":"португальский",
        "fr":"Portugais"
    }',
    '{
        "639-1":"pt",
        "639-2-T":"por",
        "639-2-B":"por",
        "639-3":"por"
    }',
    274000000,
    '{
        "continent_id": [3, 5]
    }'
),
(
    128,
    '{
        "en":"Quechua",
        "es":"quechua",
        "pt":"Quechua",
        "de":"Quechua",
        "ru":"кечуа",
        "fr":"Quechua"
    }',
    '{
        "639-1":"qu",
        "639-2-T":"que",
        "639-2-B":"que",
        "639-3":"que + 43"
    }',
    10000000,
    '{
        "continent_id": [1]
    }'
),
(
    129,
    '{
        "en":"Romansh",
        "es":"Romansh",
        "pt":"Romansh",
        "de":"Rätoromanisch",
        "ru":"Ретороманский",
        "fr":"Romanche"
    }',
    '{
        "639-1":"rm",
        "639-2-T":"roh",
        "639-2-B":"roh",
        "639-3":"roh"
    }',
    60000,
    '{
        "continent_id": [3]
    }'
),
(
    130,
    '{
        "en":"Rundi",
        "es":"Rundi",
        "pt":"Rundi",
        "de":"Rundi",
        "ru":"Рунди",
        "fr":"Rundi"
    }',
    '{
        "639-1":"rn",
        "639-2-T":"run",
        "639-2-B":"run",
        "639-3":"run"
    }',
    8800000,
    '{
        "continent_id": [1]
    }'
),
(
    131,
    '{
        "en":"Romanian",
        "es":"Rumano",
        "pt":"Romeno",
        "de":"rumänisch",
        "ru":"румынский",
        "fr":"Roumain"
    }',
    '{
        "639-1":"ro",
        "639-2-T":"ron",
        "639-2-B":"rum",
        "639-3":"ron"
    }',
    26000000,
    '{
        "continent_id": [3]
    }'
),
(
    132,
    '{
        "en":"Russian",
        "es":"Ruso",
        "pt":"Russo",
        "de":"Russisch",
        "ru":"русский",
        "fr":"russe"
    }',
    '{
        "639-1":"ru",
        "639-2-T":"rus",
        "639-2-B":"rus",
        "639-3":"rus"
    }',
    150000000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    133,
    '{
        "en":"Sanskrit",
        "es":"Sánscrito",
        "pt":"sânscrito",
        "de":"Sanskrit",
        "ru":"санскрит",
        "fr":"Sanskrit"
    }',
    '{
        "639-1":"sa",
        "639-2-T":"san",
        "639-2-B":"san",
        "639-3":"san"
    }',
    2360821,
    '{
        "continent_id": [2]
    }'
),
(
    134,
    '{
        "en":"Sardinian",
        "es":"Sardo",
        "pt":"Da Sardenha",
        "de":"Sardinisch",
        "ru":"Сардинский",
        "fr":"Sarde"
    }',
    '{
        "639-1":"sc",
        "639-2-T":"srd",
        "639-2-B":"srd",
        "639-3":"srd + 4"
    }',
    1350000,
    '{
        "continent_id": [3]
    }'
),
(
    135,
    '{
        "en":"Sindhi",
        "es":"Sindhi",
        "pt":"Sindhi",
        "de":"Sindhi",
        "ru":"Синдхи",
        "fr":"Sindhi"
    }',
    '{
        "639-1":"sd",
        "639-2-T":"snd",
        "639-2-B":"snd",
        "639-3":"snd"
    }',
    38000000,
    '{
        "continent_id": [2]
    }'
),
(
    136,
    '{
        "en":"Sami",
        "es":"Sami",
        "pt":"Sami",
        "de":"Sami",
        "ru":"Саами",
        "fr":"Sami"
    }',
    '{
        "639-1":"se",
        "639-2-T":"sme",
        "639-2-B":"sme",
        "639-3":"sme"
    }',
    25000,
    '{
        "continent_id": [3]
    }'
),
(
    137,
    '{
        "en":"Samoan",
        "es":"Samoano",
        "pt":"Samoano",
        "de":"samoanisch",
        "ru":"Самоанский",
        "fr":"Samoan"
    }',
    '{
        "639-1":"sm",
        "639-2-T":"smo",
        "639-2-B":"smo",
        "639-3":"smo"
    }',
    510000,
    '{
        "continent_id": [6]
    }'
),
(
    138,
    '{
        "en":"Sango",
        "es":"Sango",
        "pt":"Sango",
        "de":"Sango",
        "ru":"Санго",
        "fr":"Sango"
    }',
    '{
        "639-1":"sg",
        "639-2-T":"sag",
        "639-2-B":"sag",
        "639-3":"sag"
    }',
    450000,
    '{
        "continent_id": [1]
    }'
),
(
    139,
    '{
        "en":"Serbian",
        "es":"Serbio",
        "pt":"Sérvio",
        "de":"serbisch",
        "ru":"сербский",
        "fr":"serbe"
    }',
    '{
        "639-1":"sr",
        "639-2-T":"srp",
        "639-2-B":"srp",
        "639-3":"srp"
    }',
    9500000,
    '{
        "continent_id": [3]
    }'
),
(
    140,
    '{
        "en":"Gaelic",
        "es":"Gaélico",
        "pt":"Gaélico",
        "de":"gälisch",
        "ru":"Гэльский",
        "fr":"gaélique"
    }',
    '{
        "639-1":"gd",
        "639-2-T":"gla",
        "639-2-B":"gla",
        "639-3":"gla"
    }',
    87000,
    '{
        "continent_id": [3]
    }'
),
(
    141,
    '{
        "en":"Shona",
        "es":"Shona",
        "pt":"Shona",
        "de":"Shona",
        "ru":"Шона",
        "fr":"Shona"
    }',
    '{
        "639-1":"sn",
        "639-2-T":"sna",
        "639-2-B":"sna",
        "639-3":"sna"
    }',
    8300000,
    '{
        "continent_id": [1]
    }'
),
(
    142,
    '{
        "en":"Sinhala",
        "es":"Sinhala",
        "pt":"Sinhala",
        "de":"Singhalesisch",
        "ru":"Сингальский",
        "fr":"Cinghalais"
    }',
    '{
        "639-1":"si",
        "639-2-T":"sin",
        "639-2-B":"sin",
        "639-3":"sin"
    }',
    17000000,
    '{
        "continent_id": [2]
    }'
),
(
    143,
    '{
        "en":"Slovak",
        "es":"Eslovaco",
        "pt":"Eslovaco",
        "de":"slowakisch",
        "ru":"словацкий",
        "fr":"slovaque"
    }',
    '{
        "639-1":"sk",
        "639-2-T":"slk",
        "639-2-B":"slo",
        "639-3":"slk"
    }',
    5200000,
    '{
        "continent_id": [3]
    }'
),
(
    144,
    '{
        "en":"Slovenian",
        "es":"Esloveno",
        "pt":"Esloveno",
        "de":"Slowenisch",
        "ru":"словенский",
        "fr":"slovène"
    }',
    '{
        "639-1":"sl",
        "639-2-T":"slv",
        "639-2-B":"slv",
        "639-3":"slv"
    }',
    2500000,
    '{
        "continent_id": [3]
    }'
),
(
    145,
    '{
        "en":"Somali",
        "es":"somalí",
        "pt":"Somali",
        "de":"somali",
        "ru":"Сомалийский",
        "fr":"somali"
    }',
    '{
        "639-1":"so",
        "639-2-T":"som",
        "639-2-B":"som",
        "639-3":"som"
    }',
    16000000,
    '{
        "continent_id": [1]
    }'
),
(
    146,
    '{
        "en":"Sotho",
        "es":"Sotho",
        "pt":"Sotho",
        "de":"Sotho",
        "ru":"Сото",
        "fr":"Sotho"
    }',
    '{
        "639-1":"st",
        "639-2-T":"sot",
        "639-2-B":"sot",
        "639-3":"sot"
    }',
    5600000,
    '{
        "continent_id": [1]
    }'
),
(
    147,
    '{
        "en":"Spanish",
        "es":"Español",
        "pt":"Espanhol",
        "de":"Spanisch",
        "ru":"испанский",
        "fr":"Espagnol"
    }',
    '{
        "639-1":"es",
        "639-2-T":"spa",
        "639-2-B":"spa",
        "639-3":"spa"
    }',
    483000000,
    '{
        "continent_id": [3, 5]
    }'
),
(
    148,
    '{
        "en":"Sundanese",
        "es":"Sundanés",
        "pt":"Sudanês",
        "de":"Sundanais",
        "ru":"Суданский",
        "fr":"Sundanais"
    }',
    '{
        "639-1":"su",
        "639-2-T":"sun",
        "639-2-B":"sun",
        "639-3":"sun"
    }',
    40000000,
    '{
        "continent_id": [2]
    }'
),
(
    149,
    '{
        "en":"Swahili",
        "es":"swahili",
        "pt":"Suaíli",
        "de":"Swahili",
        "ru":"суахили",
        "fr":"Swahili"
    }',
    '{
        "639-1":"sw",
        "639-2-T":"swa",
        "639-2-B":"swa",
        "639-3":"swa + 2"
    }',
    150000000,
    '{
        "continent_id": [1]
    }'
),
(
    150,
    '{
        "en":"Swati",
        "es":"Swati",
        "pt":"Swati",
        "de":"Swati",
        "ru":"Свати",
        "fr":"Swati"
    }',
    '{
        "639-1":"ss",
        "639-2-T":"ssw",
        "639-2-B":"ssw",
        "639-3":"ssw"
    }',
    2300000,
    '{
        "continent_id": [1]
    }'
),
(
    151,
    '{
        "en":"Swedish",
        "es":"Sueco",
        "pt":"Sueco",
        "de":"Schwedisch",
        "ru":"Шведский",
        "fr":"Suédois"
    }',
    '{
        "639-1":"sv",
        "639-2-T":"swe",
        "639-2-B":"swe",
        "639-3":"swe"
    }',
    10000000,
    '{
        "continent_id": [3]
    }'
),
(
    152,
    '{
        "en":"Tamil",
        "es":"Tamil",
        "pt":"tâmil",
        "de":"Tamil",
        "ru":"Тамильский",
        "fr":"Tamil"
    }',
    '{
        "639-1":"ta",
        "639-2-T":"tam",
        "639-2-B":"tam",
        "639-3":"tam"
    }',
    75000000,
    '{
        "continent_id": [2]
    }'
),
(
    153,
    '{
        "en":"Telugu",
        "es":"Telugu",
        "pt":"Telugu",
        "de":"Telugu",
        "ru":"телугу",
        "fr":"Telugu"
    }',
    '{
        "639-1":"te",
        "639-2-T":"tel",
        "639-2-B":"tel",
        "639-3":"tel"
    }',
    82000000,
    '{
        "continent_id": [2]
    }'
),
(
    154,
    '{
        "en":"Tajik",
        "es":"Tayiko",
        "pt":"Tadjique",
        "de":"Tadschikisch",
        "ru":"Таджикский",
        "fr":"Tadjik"
    }',
    '{
        "639-1":"tg",
        "639-2-T":"tgk",
        "639-2-B":"tgk",
        "639-3":"tgk"
    }',
    8400000,
    '{
        "continent_id": [2]
    }'
),
(
    155,
    '{
        "en":"Thai",
        "es":"Tailandés",
        "pt":"Tailandês",
        "de":"Thai",
        "ru":"Тайский",
        "fr":"thaïlandais"
    }',
    '{
        "639-1":"th",
        "639-2-T":"tha",
        "639-2-B":"tha",
        "639-3":"tha"
    }',
    36000000,
    '{
        "continent_id": [2]
    }'
),
(
    156,
    '{
        "en":"Tigrinya",
        "es":"Tigrinya",
        "pt":"Tigrinya",
        "de":"Tigrinya",
        "ru":"Тигринья",
        "fr":"Tigrinya"
    }',
    '{
        "639-1":"ti",
        "639-2-T":"tir",
        "639-2-B":"tir",
        "639-3":"tir"
    }',
    9000000,
    '{
        "continent_id": [1]
    }'
),
(
    157,
    '{
        "en":"Tibetan",
        "es":"Tibetano",
        "pt":"Tibetano",
        "de":"Tibetisch",
        "ru":"тибетский",
        "fr":"Tibétain"
    }',
    '{
        "639-1":"bo",
        "639-2-T":"bod",
        "639-2-B":"tib",
        "639-3":"bod"
    }',
    1200000,
    '{
        "continent_id": [2]
    }'
),
(
    158,
    '{
        "en":"Turkmen",
        "es":"Turcomano",
        "pt":"Turcomano",
        "de":"Turkmenen",
        "ru":"туркменский",
        "fr":"Turkmène"
    }',
    '{
        "639-1":"tk",
        "639-2-T":"tuk",
        "639-2-B":"tuk",
        "639-3":"tuk"
    }',
    6700000,
    '{
        "continent_id": [2]
    }'
),
(
    159,
    '{
        "en":"Tagalog",
        "es":"Tagalo",
        "pt":"Tagalo",
        "de":"Tagalog",
        "ru":"Тагальский",
        "fr":"Tagalog"
    }',
    '{
        "639-1":"tl",
        "639-2-T":"tgl",
        "639-2-B":"tgl",
        "639-3":"tgl"
    }',
    23800000,
    '{
        "continent_id": [2]
    }'
),
(
    160,
    '{
        "en":"Tswana",
        "es":"Tswana",
        "pt":"Tswana",
        "de":"Tswana",
        "ru":"Тсвана",
        "fr":"Tswana"
    }',
    '{
        "639-1":"tn",
        "639-2-T":"tsn",
        "639-2-B":"tsn",
        "639-3":"tsn"
    }',
    4100000,
    '{
        "continent_id": [1]
    }'
),
(
    161,
    '{
        "en":"Tonga",
        "es":"Tonga",
        "pt":"Tonga",
        "de":"Tonga",
        "ru":"Тонга",
        "fr":"Tonga"
    }',
    '{
        "639-1":"to",
        "639-2-T":"ton",
        "639-2-B":"ton",
        "639-3":"ton"
    }',
    187000,
    '{
        "continent_id": [6]
    }'
),
(
    162,
    '{
        "en":"Turkish",
        "es":"Turco",
        "pt":"Turco",
        "de":"Türkisch",
        "ru":"турецкий",
        "fr":"Turc"
    }',
    '{
        "639-1":"tr",
        "639-2-T":"tur",
        "639-2-B":"tur",
        "639-3":"tur"
    }',
    75700000,
    '{
        "continent_id": [3]
    }'
),
(
    163,
    '{
        "en":"Tsonga",
        "es":"Tsonga",
        "pt":"Tsonga",
        "de":"Tsonga",
        "ru":"Тсонга",
        "fr":"Tsonga"
    }',
    '{
        "639-1":"ts",
        "639-2-T":"tso",
        "639-2-B":"tso",
        "639-3":"tso"
    }',
    12000000,
    '{
        "continent_id": [1]
    }'
),
(
    164,
    '{
        "en":"Tatar",
        "es":"Tártaro",
        "pt":"Tártaro",
        "de":"Tatar",
        "ru":"Татарский",
        "fr":"Tatar"
    }',
    '{
        "639-1":"tt",
        "639-2-T":"tat",
        "639-2-B":"tat",
        "639-3":"tat"
    }',
    5200000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    165,
    '{
        "en":"Twi",
        "es":"Twi",
        "pt":"Twi",
        "de":"Twi",
        "ru":"Тви",
        "fr":"Twi"
    }',
    '{
        "639-1":"tw",
        "639-2-T":"twi",
        "639-2-B":"twi",
        "639-3":"twi"
    }',
    947000,
    '{
        "continent_id": [1]
    }'
),
(
    166,
    '{
        "en":"Tahitian",
        "es":"Tahitiano",
        "pt":"Taitiano",
        "de":"Tahitisch",
        "ru":"Таитянский",
        "fr":"Tahitien"
    }',
    '{
        "639-1":"ty",
        "639-2-T":"tah",
        "639-2-B":"tah",
        "639-3":"tah"
    }',
    68260,
    '{
        "continent_id": [6]
    }'
),
(
    167,
    '{
        "en":"Uighur",
        "es":"Uigur",
        "pt":"Uigur",
        "de":"Uighur",
        "ru":"Уйгурский",
        "fr":"Ouïghour"
    }',
    '{
        "639-1":"ug",
        "639-2-T":"uig",
        "639-2-B":"uig",
        "639-3":"uig"
    }',
    10000000,
    '{
        "continent_id": [2]
    }'
),
(
    168,
    '{
        "en":"Ukrainian",
        "es":"Ucranio",
        "pt":"Ucraniano",
        "de":"ukrainisch",
        "ru":"украинец",
        "fr":"ukrainien"
    }',
    '{
        "639-1":"uk",
        "639-2-T":"ukr",
        "639-2-B":"ukr",
        "639-3":"ukr"
    }',
    40000000,
    '{
        "continent_id": [3]
    }'
),
(
    169,
    '{
        "en":"Urdu",
        "es":"Urdu",
        "pt":"urdu",
        "de":"Urdu",
        "ru":"Урду",
        "fr":"Ourdou"
    }',
    '{
        "639-1":"ur",
        "639-2-T":"urd",
        "639-2-B":"urd",
        "639-3":"urd"
    }',
    68620000,
    '{
        "continent_id": [2]
    }'
),
(
    170,
    '{
        "en":"Uzbek",
        "es":"Uzbeko",
        "pt":"Uzbeque",
        "de":"Usbekisch",
        "ru":"Узбекский",
        "fr":"Ouzbek"
    }',
    '{
        "639-1":"uz",
        "639-2-T":"uzb",
        "639-2-B":"uzb",
        "639-3":"uzb + 2"
    }',
    27000000,
    '{
        "continent_id": [2]
    }'
),
(
    171,
    '{
        "en":"Venda",
        "es":"Venda",
        "pt":"Venda",
        "de":"Venda",
        "ru":"Венда",
        "fr":"Venda"
    }',
    '{
        "639-1":"ve",
        "639-2-T":"ven",
        "639-2-B":"ven",
        "639-3":"ven"
    }',
    1300000,
    '{
        "continent_id": [1]
    }'
),
(
    172,
    '{
        "en":"Vietnamese",
        "es":"vietnamita",
        "pt":"vietnamita",
        "de":"Vietnamesisch",
        "ru":"вьетнамский",
        "fr":"Vietnamien"
    }',
    '{
        "639-1":"vi",
        "639-2-T":"vie",
        "639-2-B":"vie",
        "639-3":"vie"
    }',
    90000000,
    '{
        "continent_id": [2]
    }'
),
(
    173,
    '{
        "en":"Volapük",
        "es":"Volapük",
        "pt":"Volapük",
        "de":"Volapük",
        "ru":"Волапюк",
        "fr":"Volapük"
    }',
    '{
        "639-1":"vo",
        "639-2-T":"vol",
        "639-2-B":"vol",
        "639-3":"vol"
    }',
    20,
    '{
        "continent_id": [3, 4]
    }'
),
(
    174,
    '{
        "en":"Walloon",
        "es":"Valonia",
        "pt":"valão",
        "de":"wallonisch",
        "ru":"валлонский",
        "fr":"Wallon"
    }',
    '{
        "639-1":"wa",
        "639-2-T":"wln",
        "639-2-B":"wln",
        "639-3":"wln"
    }',
    600000,
    '{
        "continent_id": [3]
    }'
),
(
    175,
    '{
        "en":"Welsh",
        "es":"Galés",
        "pt":"galês",
        "de":"Walisisch",
        "ru":"валлийский",
        "fr":"gallois"
    }',
    '{
        "639-1":"cy",
        "639-2-T":"cym",
        "639-2-B":"wel",
        "639-3":"cym"
    }',
    1000000,
    '{
        "continent_id": [3]
    }'
),
(
    176,
    '{
        "en":"Wolof",
        "es":"Wolof",
        "pt":"Wolof",
        "de":"Wolof",
        "ru":"Волоф",
        "fr":"Wolof"
    }',
    '{
        "639-1":"wo",
        "639-2-T":"wol",
        "639-2-B":"wol",
        "639-3":"wol"
    }',
    5454000,
    '{
        "continent_id": [1]
    }'
),
(
    177,
    '{
        "en":"Western Frisian",
        "es":"Frisón occidental",
        "pt":"Frísio Ocidental",
        "de":"Westfriesisch",
        "ru":"Западно-фризский",
        "fr":"Frison occidental"
    }',
    '{
        "639-1":"fy",
        "639-2-T":"fry",
        "639-2-B":"fry",
        "639-3":"fry"
    }',
    470000,
    '{
        "continent_id": [3]
    }'
),
(
    178,
    '{
        "en":"Xhosa",
        "es":"Xhosa",
        "pt":"Xhosa",
        "de":"Xhosa",
        "ru":"Коса",
        "fr":"Xhosa"
    }',
    '{
        "639-1":"xh",
        "639-2-T":"xho",
        "639-2-B":"xho",
        "639-3":"xho"
    }',
    8200000,
    '{
        "continent_id": [1]
    }'
),
(
    179,
    '{
        "en":"Yiddish",
        "es":"yídish",
        "pt":"Iídiche",
        "de":"Jiddisch",
        "ru":"идиш",
        "fr":"yiddish"
    }',
    '{
        "639-1":"yi",
        "639-2-T":"yid",
        "639-2-B":"yid",
        "639-3":"yid + 2"
    }',
    1500000,
    '{
        "continent_id": [2, 3]
    }'
),
(
    180,
    '{
        "en":"Yoruba",
        "es":"Yoruba",
        "pt":"Ioruba",
        "de":"Yoruba",
        "ru":"Йоруба",
        "fr":"Yoruba"
    }',
    '{
        "639-1":"yo",
        "639-2-T":"yor",
        "639-2-B":"yor",
        "639-3":"yor"
    }',
    50000000,
    '{
        "continent_id": [1]
    }'
),
(
    181,
    '{
        "en":"Zhuang",
        "es":"Zhuang",
        "pt":"Zhuang",
        "de":"Zhuang",
        "ru":"Чжуан",
        "fr":"Zhuang"
    }',
    '{
        "639-1":"za",
        "639-2-T":"zha",
        "639-2-B":"zha",
        "639-3":"zha + 16"
    }',
    5600000,
    '{
        "continent_id": [2]
    }'
),
(
    182,
    '{
        "en":"Zulu",
        "es":"zulú",
        "pt":"zulu",
        "de":"Zulu",
        "ru":"Зулусский",
        "fr":"zoulou"
    }',
    '{
        "639-1":"zu",
        "639-2-T":"zul",
        "639-2-B":"zul",
        "639-3":"zul"
    }',
    12000000,
    '{
        "continent_id": [1]
    }'
);
